# Generated by Django 4.2.23 on 2025-11-05 01:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fridge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Main Fridge",
                        help_text='A friendly name for the fridge (e.g., "Kitchen Fridge", "Garage Freezer").',
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fridge_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="FridgeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        help_text="The number or amount of this item.",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Quantity must be at least 1."
                            )
                        ],
                    ),
                ),
                (
                    "fridge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.fridge",
                    ),
                ),
            ],
            options={
                "unique_together": {("fridge", "name")},
            },
        ),
    ]
